version: '3.3'
services:
  triton:
    image: moyix/triton_with_ft:22.09
    command: bash -c "CUDA_VISIBLE_DEVICES=${GPUS} mpirun -n 1 --allow-run-as-root /opt/tritonserver/bin/tritonserver --model-repository=/model"
    shm_size: '2gb'
    volumes:
      - ${MODEL_DIR}:/model
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  copilot_proxy:
    image: moyix/copilot_proxy:latest
    # For local build
#    build:
#      context: .
#      dockerfile: copilot_proxy/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_EXTERNAL_PORT}:5000"
