version: '3.3'
services:
  triton:
    image: moyix/triton_with_ft:22.09
    command: bash -c "CUDA_VISIBLE_DEVICES=${GPUS} mpirun -n 1 --allow-run-as-root /opt/tritonserver/bin/tritonserver --model-repository=/model"
    shm_size: '2gb'
    volumes:
      - ${MODEL_DIR}:/model
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  copilot_proxy:
    image: moyix/copilot_proxy:latest
    command: python3 -m flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
